python zs_inference.py --shots 5 --task stance --model Q14B --prompt_lang ar --save_path ./zs_preds #379
python zs_inference.py --shots 5 --task pos_tagging --model Q14B --prompt_lang ar --save_path ./zs_preds #680
python zs_inference.py --shots 5 --task hate --model Q14B --prompt_lang ar --save_path ./zs_preds #1000
python zs_inference.py --shots 5 --task sarcasm --model Q14B --prompt_lang ar --save_path ./zs_preds #2110
python zs_inference.py --shots 5 --task paraphrasing --model Q14B --prompt_lang en --save_path ./zs_preds #1010
python zs_inference.py --shots 5 --task claim --model Q14B --prompt_lang ar --save_path ./zs_preds #456
python zs_inference.py --shots 5 --task GQA --model Q14B --prompt_lang en --save_path ./zs_preds #921
python zs_inference.py --shots 5 --task offensive --model Q14B --prompt_lang en --save_path ./zs_preds #1000
python zs_inference.py --shots 5 --task dialect --model Q14B --prompt_lang ar --save_path ./zs_preds #2110
python zs_inference.py --shots 5 --task sqs --model Q14B --prompt_lang ar --save_path ./zs_preds #3715
python zs_inference.py --shots 5 --task wsd --model Q14B --prompt_lang ar --save_path ./zs_preds #6220
python zs_inference.py --shots 5 --task summarization --model Q14B --prompt_lang en --save_path ./zs_preds #6220
python zs_inference.py --shots 5 --task translation --model Q14B --prompt_lang ar --save_path ./zs_preds #6220
python zs_inference.py --shots 5 --task transliteration --model Q14B --prompt_lang ar --save_path ./zs_preds #6220
python zs_inference.py --shots 5 --task sentiment --model Q14B --prompt_lang ar --save_path ./zs_preds #6220