python zs_inference.py --shots 5 --task stance --model R1 --prompt_lang ar --save_path ./zs_preds #379
python zs_inference.py --shots 5 --task pos_tagging --model R1 --prompt_lang ar --save_path ./zs_preds #680
python zs_inference.py --shots 5 --task hate --model R1 --prompt_lang ar --save_path ./zs_preds #1000
python zs_inference.py --shots 5 --task sarcasm --model R1 --prompt_lang ar --save_path ./zs_preds #2110
python zs_inference.py --shots 5 --task paraphrasing --model R1 --prompt_lang en --save_path ./zs_preds #1010
python zs_inference.py --shots 5 --task claim --model R1 --prompt_lang ar --save_path ./zs_preds #456
python zs_inference.py --shots 5 --task GQA --model R1 --prompt_lang en --save_path ./zs_preds #921
python zs_inference.py --shots 5 --task offensive --model R1 --prompt_lang en --save_path ./zs_preds #1000
python zs_inference.py --shots 5 --task dialect --model R1 --prompt_lang ar --save_path ./zs_preds #2110
python zs_inference.py --shots 5 --task sqs --model R1 --prompt_lang ar --save_path ./zs_preds #3715
python zs_inference.py --shots 5 --task wsd --model R1 --prompt_lang ar --save_path ./zs_preds #6220
python zs_inference.py --shots 5 --task summarization --model R1 --prompt_lang en --save_path ./zs_preds #6220
python zs_inference.py --shots 5 --task translation --model R1 --prompt_lang ar --save_path ./zs_preds #6220
python zs_inference.py --shots 5 --task transliteration --model R1 --prompt_lang ar --save_path ./zs_preds #6220
python zs_inference.py --shots 5 --task sentiment --model R1 --prompt_lang ar --save_path ./zs_preds #6220