python zs_inference.py --task stance --model R1 --prompt_lang ar --save_path ./zs_preds #379
python zs_inference.py --task pos_tagging --model R1 --prompt_lang ar --save_path ./zs_preds #680
python zs_inference.py --task hate --model R1 --prompt_lang ar --save_path ./zs_preds #1000
python zs_inference.py --task sarcasm --model R1 --prompt_lang ar --save_path ./zs_preds #2110
python zs_inference.py --task paraphrasing --model R1 --prompt_lang en --save_path ./zs_preds #1010
python zs_inference.py --task claim --model R1 --prompt_lang ar --save_path ./zs_preds #456
python zs_inference.py --task GQA --model R1 --prompt_lang en --save_path ./zs_preds #921
python zs_inference.py --task offensive --model R1 --prompt_lang en --save_path ./zs_preds #1000
python zs_inference.py --task dialect --model R1 --prompt_lang ar --save_path ./zs_preds #2110
python zs_inference.py --task sqs --model R1 --prompt_lang ar --save_path ./zs_preds #3715
python zs_inference.py --task wsd --model R1 --prompt_lang ar --save_path ./zs_preds #6220
python zs_inference.py --task summarization --model R1 --prompt_lang en --save_path ./zs_preds #6220
python zs_inference.py --task translation --model R1 --prompt_lang ar --save_path ./zs_preds #6220
python zs_inference.py --task transliteration --model R1 --prompt_lang ar --save_path ./zs_preds #6220
python zs_inference.py --task sentiment --model R1 --prompt_lang ar --save_path ./zs_preds #6220