python zs_inference.py --task stance --model V3 --prompt_lang ar --save_path ./zs_preds #379
python zs_inference.py --task pos_tagging --model V3 --prompt_lang ar --save_path ./zs_preds #680
python zs_inference.py --task hate --model V3 --prompt_lang ar --save_path ./zs_preds #1000
python zs_inference.py --task sarcasm --model V3 --prompt_lang ar --save_path ./zs_preds #2110
python zs_inference.py --task paraphrasing --model V3 --prompt_lang en --save_path ./zs_preds #1010
python zs_inference.py --task claim --model V3 --prompt_lang ar --save_path ./zs_preds #456
python zs_inference.py --task GQA --model V3 --prompt_lang en --save_path ./zs_preds #921
python zs_inference.py --task offensive --model V3 --prompt_lang en --save_path ./zs_preds #1000
python zs_inference.py --task dialect --model V3 --prompt_lang ar --save_path ./zs_preds #2110
python zs_inference.py --task sqs --model V3 --prompt_lang ar --save_path ./zs_preds #3715
python zs_inference.py --task wsd --model V3 --prompt_lang ar --save_path ./zs_preds #6220
python zs_inference.py --task summarization --model V3 --prompt_lang en --save_path ./zs_preds #6220
python zs_inference.py --task translation --model V3 --prompt_lang ar --save_path ./zs_preds #6220
python zs_inference.py --task transliteration --model V3 --prompt_lang ar --save_path ./zs_preds #6220
python zs_inference.py --task sentiment --model V3 --prompt_lang ar --save_path ./zs_preds #6220